'use strict';
$('#main>div').hide();
$(document).ready(function(){
    $('#ibtn').click(function(){
        $('#iexp').toggle();
    });
});
$(document).ready(function(){
    $('#sbtn').click(function(){
        $('#sexp').toggle();
    });
});
$(document).ready(function(){
    $('#hbtn').click(function(){
        $('#hexp').toggle();
    });
});
$(document).ready(function(){
    $('#dbtn').click(function(){
        $('#dexp').toggle();
    });
});
$(document).ready(function(){
    $('#tbtn').click(function(){
        $('#texp').toggle();
    });
});
$(document).ready(function(){
    $('#tibtn').click(function(){
        $('#tiexp').toggle();
    });
});
